name: Awesome loker CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  start_build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install dependencies
      run : npm install
    - name: Start update loker
      run : npm run update
    - name: Commit and push if it changed
      run: |-
        git config user.name "satyawikananda"
        git config user.email "${{ secrets.EMAIL }}"
        git add -A
        timestamp=$(date -u)
        git commit -m "chore(loker): Update loker" || exit 0
        git push
